import DealBrief from "@/components/DealBrief";

const jsonLd = {
  "@context": "https://schema.org",
  "@type": "SoftwareApplication",
  name: "DealBrief",
  url: "https://www.getdealbrief.com",
  applicationCategory: "BusinessApplication",
  operatingSystem: "Web",
  description:
    "Pre-offer property research reports for multifamily real estate investors. Instantly pulls tax assessments, permit history, FEMA flood zone, crime grades, demographics, and generates a debt service analysis PDF.",
  offers: {
    "@type": "Offer",
    price: "49",
    priceCurrency: "USD",
    description: "Per-report pricing for multifamily property research",
  },
  featureList: [
    "Tax assessment & ownership history",
    "Permit history lookup",
    "FEMA flood zone classification",
    "Crime grade analysis",
    "Census demographics",
    "Walk Score, Bike Score, Transit Score",
    "Debt service coverage ratio scenarios",
    "Cap rate analysis",
    "PDF report generation",
  ],
  audience: {
    "@type": "Audience",
    audienceType: "Real estate investors, multifamily buyers, property syndicators",
  },
  areaServed: [
    "Dallas-Fort Worth, TX",
    "Houston, TX",
    "San Antonio, TX",
    "Austin, TX",
    "El Paso, TX",
    "Phoenix, AZ",
    "Denver, CO",
    "Aurora, CO",
    "Lakewood, CO",
    "Thornton, CO",
    "Centennial, CO",
    "Boulder, CO",
    "Wheat Ridge, CO",
    "Highlands Ranch, CO",
    "Las Vegas, NV",
    "Henderson, NV",
    "Oklahoma City, OK",
    "Edmond, OK",
    "Norman, OK",
    "Moore, OK",
    "Yukon, OK",
    "Midwest City, OK",
    "Tulsa, OK",
    "Broken Arrow, OK",
    "Bixby, OK",
    "Owasso, OK",
    "Charlotte, NC",
    "Raleigh, NC",
    "Durham, NC",
    "Atlanta, GA",
    "Louisville, KY",
    "Lexington, KY",
    "Covington, KY",
    "Florence, KY",
    "Newport, KY",
    "Tampa, FL",
    "Orlando, FL",
    "Jacksonville, FL",
    "Miami, FL",
    "Fort Lauderdale, FL",
    "West Palm Beach, FL",
    "Philadelphia, PA",
    "Toledo, OH",
    "Perrysburg, OH",
    "Cleveland, OH",
    "Akron, OH",
    "Columbus, OH",
    "Cincinnati, OH",
    "Hamilton, OH",
    "Dayton, OH",
    "Kettering, OH",
    "Beavercreek, OH",
    "Fairborn, OH",
    "Huber Heights, OH",
    "Centerville, OH",
    "Nashville, TN",
    "Franklin, TN",
    "Murfreesboro, TN",
    "Memphis, TN-MS",
    "Memphis, TN",
    "Hernando, MS",
    "Olive Branch, MS",
    "Southaven, MS",
    "Kansas City, MO-KS",
    "Kansas City, MO",
    "Kansas City, KS",
    "St. Louis, MO",
    "Clayton, MO",
    "Kirkwood, MO",
    "Chesterfield, MO",
    "Ferguson, MO",
    "Florissant, MO",
    "St. Charles, MO",
    "Wentzville, MO",
    "Independence, MO",
    "Lee's Summit, MO",
    "Overland Park, KS",
    "Olathe, KS",
    "Indianapolis, IN",
    "Carmel, IN",
    "Fishers, IN",
    "Noblesville, IN",
  ],
};

export default function Home() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <DealBrief />
    </>
  );
}
